# Form implementation generated from reading ui file 'C:\Users\user\Desktop\exampleUI\example_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color :#E9E8E9;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_6.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(20, 5, 0, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.sf1Display = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.sf1Display.setFont(font)
        self.sf1Display.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.sf1Display.setObjectName("sf1Display")
        self.verticalLayout_6.addWidget(self.sf1Display)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(20, 5, 0, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.cm1Display = QtWidgets.QLabel(parent=self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.cm1Display.setFont(font)
        self.cm1Display.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.cm1Display.setObjectName("cm1Display")
        self.verticalLayout_7.addWidget(self.cm1Display)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setContentsMargins(20, 5, 0, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.ls1Display = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.ls1Display.setFont(font)
        self.ls1Display.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.ls1Display.setObjectName("ls1Display")
        self.verticalLayout_8.addWidget(self.ls1Display)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_9.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setContentsMargins(20, 5, 20, 15)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.sf1Input = QtWidgets.QLineEdit(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.sf1Input.setFont(font)
        self.sf1Input.setStyleSheet("QLineEdit{\n"
"color: #000000;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.sf1Input.setObjectName("sf1Input")
        self.verticalLayout_9.addWidget(self.sf1Input)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_10.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setContentsMargins(20, 5, 20, 15)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.cm1Input = QtWidgets.QLineEdit(parent=self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.cm1Input.setFont(font)
        self.cm1Input.setStyleSheet("QLineEdit{\n"
"color: #000000;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.cm1Input.setObjectName("cm1Input")
        self.verticalLayout_10.addWidget(self.cm1Input)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_11.setStyleSheet("QFrame{\n"
"border-radius: 8px;\n"
"border: 1px solid #EBEFF2;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setContentsMargins(20, 5, 20, 15)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"border: none;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.ls1Input = QtWidgets.QLineEdit(parent=self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.ls1Input.setFont(font)
        self.ls1Input.setStyleSheet("QLineEdit{\n"
"color: #000000;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.ls1Input.setObjectName("ls1Input")
        self.verticalLayout_11.addWidget(self.ls1Input)
        self.verticalLayout_5.addWidget(self.frame_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(5, 20, 5, 0)
        self.verticalLayout_3.setSpacing(50)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: #000000;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sf1Btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.sf1Btn.setMinimumSize(QtCore.QSize(0, 50))
        self.sf1Btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.sf1Btn.setFont(font)
        self.sf1Btn.setStyleSheet("QPushButton{\n"
"border-radius: 4px;\n"
"background-color: rgba(169,16,142, 255);\n"
"color: #ffffff;\n"
"border: 1px solid #954186;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(159,6,132, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(149,0,122, 255);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgba(225,229,232,255);\n"
"color: rgba(255,255,255,255);\n"
"border: none;\n"
"}")
        self.sf1Btn.setObjectName("sf1Btn")
        self.verticalLayout.addWidget(self.sf1Btn)
        self.cm1Btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.cm1Btn.setMinimumSize(QtCore.QSize(0, 50))
        self.cm1Btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.cm1Btn.setFont(font)
        self.cm1Btn.setStyleSheet("QPushButton{\n"
"border-radius: 4px;\n"
"background-color: rgba(169,16,142, 255);\n"
"color: #ffffff;\n"
"border: 1px solid #954186;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(159,6,132, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(149,0,122, 255);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgba(225,229,232,255);\n"
"color: rgba(255,255,255,255);\n"
"border: none;\n"
"}")
        self.cm1Btn.setObjectName("cm1Btn")
        self.verticalLayout.addWidget(self.cm1Btn)
        self.ls1Btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.ls1Btn.setMinimumSize(QtCore.QSize(0, 50))
        self.ls1Btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.ls1Btn.setFont(font)
        self.ls1Btn.setStyleSheet("QPushButton{\n"
"border-radius: 4px;\n"
"background-color: rgba(169,16,142, 255);\n"
"color: #ffffff;\n"
"border: 1px solid #954186;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(159,6,132, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(149,0,122, 255);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: rgba(225,229,232,255);\n"
"color: rgba(255,255,255,255);\n"
"border: none;\n"
"}")
        self.ls1Btn.setObjectName("ls1Btn")
        self.verticalLayout.addWidget(self.ls1Btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 258, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "SimpleFunctionOne"))
        self.sf1Display.setText(_translate("MainWindow", "Output will be displayed here"))
        self.label_5.setText(_translate("MainWindow", "ComplexModuleOne"))
        self.cm1Display.setText(_translate("MainWindow", "Output will be displayed here"))
        self.label_6.setText(_translate("MainWindow", "LocalServiceOne"))
        self.ls1Display.setText(_translate("MainWindow", "Output will be displayed here"))
        self.label_7.setText(_translate("MainWindow", "SimpleFunctionOne Input"))
        self.sf1Input.setText(_translate("MainWindow", "Enter your input here"))
        self.label_8.setText(_translate("MainWindow", "ComplexModuleOne Input"))
        self.cm1Input.setText(_translate("MainWindow", "Enter your input here"))
        self.label_9.setText(_translate("MainWindow", "LocalServiceOne Input"))
        self.ls1Input.setText(_translate("MainWindow", "Enter your input here"))
        self.label_2.setText(_translate("MainWindow", "ExampleUI"))
        self.label_3.setText(_translate("MainWindow", "Developed by Sean Lee"))
        self.label.setText(_translate("MainWindow", "Functions"))
        self.sf1Btn.setText(_translate("MainWindow", "SimpleFunctionOne"))
        self.cm1Btn.setText(_translate("MainWindow", "ComplexModuleOne"))
        self.ls1Btn.setText(_translate("MainWindow", "LocalServiceOne"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
